.TH "bug" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
.PP

.IP "\fBMember \fBMyLibrary::Example::test\fP (const std::string &test)\fP" 1c
example bug 
.IP "\fBMember \fBMyLibrary::SubclassExample< TemplatedClass >::virtualfunc\fP () override\fP" 1c
second bug 
.PP

