.TH "Documentation/Code/doxygen-awesome-css Directory Reference" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documentation/Code/doxygen-awesome-css Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdocs\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.in -1c
