.TH "Documentation/Code/doxygen-awesome-css/include/MyLibrary/example.hpp" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documentation/Code/doxygen-awesome-css/include/MyLibrary/example.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::Example\fP"
.br
.RI "\fBExample\fP class to demonstrate the features of the custom CSS\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMyLibrary\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMyLibrary::Color\fP { \fBMyLibrary::red\fP, \fBMyLibrary::green\fP, \fBMyLibrary::blue\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
