.TH "files.SaveFile" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
files.SaveFile
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBfiles\&.UserData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBsave_file\fP, bool auto_load=True)"
.br
.ti -1c
.RI "None \fBload\fP (self)"
.br
.ti -1c
.RI "None \fBsave\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsave_file\fP"
.br
.ti -1c
.RI "\fBsave_data\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBsave_file\fP = 'save\&.json'"
.br
.ti -1c
.RI "dict \fBsave_data\fP = {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBfiles\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None files\&.SaveFile\&.__init__ ( self, str save_file, bool  auto_load = \fCTrue\fP)"

.PP
.nf
Initialises the save file class

@param save_file: The file to save the data to, will be created if it does not exist
@param auto_load: If the file should be loaded automatically when the class is initialised,
by default this is True

.fi
.PP
 
.PP
Reimplemented in \fBfiles\&.UserData\fP\&.
.PP
Definition at line \fB39\fP of file \fBfiles\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None files\&.SaveFile\&.load ( self)"

.PP
.nf
Loads the data from the save file into the save_data dictionary\&. If the file is corrupt or does not exist
then the save_data dictionary will remain the same as its previous state\&. The caller of this function needs to
manually load the varibles from the save_data dictionary, it is also good practice to check if the types are
correct as JSON can be manipulated\&.

@return: None, this function will return if the file is corrupt or does not exist

.fi
.PP
 
.PP
Definition at line \fB54\fP of file \fBfiles\&.py\fP\&.
.SS " None files\&.SaveFile\&.save ( self)"

.PP
.nf
Saves the data from the save_data dictionary to the save file\&. If the file does not exist then it will be
created\&. The save_data dictionary needs to be set before this function is called, do this by setting the
save_data dictionary to the __dict__ of the subclass\&. Note: do not need to remove the save_data dictionary
from the save_data dictionary as this is done automatically\&.

.fi
.PP
 
.PP
Reimplemented in \fBfiles\&.UserData\fP\&.
.PP
Definition at line \fB90\fP of file \fBfiles\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "dict files\&.SaveFile\&.save_data = {}\fC [static]\fP"

.PP
Definition at line \fB37\fP of file \fBfiles\&.py\fP\&.
.SS "files\&.SaveFile\&.save_data"

.PP
Definition at line \fB73\fP of file \fBfiles\&.py\fP\&.
.SS "str files\&.SaveFile\&.save_file = 'save\&.json'\fC [static]\fP"

.PP
Definition at line \fB36\fP of file \fBfiles\&.py\fP\&.
.SS "files\&.SaveFile\&.save_file"

.PP
Definition at line \fB47\fP of file \fBfiles\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
