.TH "Maxs_Modules/files.py" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Maxs_Modules/files.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfiles\&.SaveFile\fP"
.br
.ti -1c
.RI "class \fBfiles\&.UserData\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfiles\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "dict \fBfiles\&.load_questions_from_file\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBfiles\&.offline_questions_file\fP = 'ProgramData/questions\&.json'"
.br
.ti -1c
.RI "str \fBfiles\&.data_folder\fP = 'UserData/'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
