.TH "files" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
files
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSaveFile\fP"
.br
.ti -1c
.RI "class \fBUserData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "dict \fBload_questions_from_file\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBoffline_questions_file\fP = 'ProgramData/questions\&.json'"
.br
.ti -1c
.RI "str \fBdata_folder\fP = 'UserData/'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " dict files\&.load_questions_from_file ()"

.PP
.nf
Loads a json array of questions from the offline questions file specified in the offline_questions_file variable\&.
This is just a downloaded JSON api response from the Open Trivia Database API\&.

@return: JSON object of questions

.fi
.PP
 
.PP
Definition at line \fB16\fP of file \fBfiles\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "str files\&.data_folder = 'UserData/'"

.PP
Definition at line \fB10\fP of file \fBfiles\&.py\fP\&.
.SS "str files\&.offline_questions_file = 'ProgramData/questions\&.json'"

.PP
Definition at line \fB9\fP of file \fBfiles\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
