.TH "Maxs_Modules/game.py" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Maxs_Modules/game.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgame\&.Question\fP"
.br
.ti -1c
.RI "class \fBgame\&.User\fP"
.br
.ti -1c
.RI "class \fBgame\&.Bot\fP"
.br
.ti -1c
.RI "class \fBgame\&.Game\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgame\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgame\&.generate_new_save_file\fP ()"
.br
.ti -1c
.RI "def \fBgame\&.get_saved_games\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBgame\&.data_folder\fP = 'UserData/Games/'"
.br
.ti -1c
.RI "int \fBgame\&.category_offset\fP = 9"
.br
.ti -1c
.RI "int \fBgame\&.max_number_of_questions\fP = 50"
.br
.ti -1c
.RI "tuple \fBgame\&.quiz_categories\fP"
.br
.ti -1c
.RI "bool \fBgame\&.host_a_server_by_default\fP = False"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
