.TH "game.Game" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.Game
.SH SYNOPSIS
.br
.PP
.PP
Inherits SaveFile\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str quiz_save=None)"
.br
.ti -1c
.RI "None \fBload_from_saved\fP (self)"
.br
.ti -1c
.RI "None \fBset_settings_default\fP (self)"
.br
.ti -1c
.RI "None \fBset_settings\fP (self)"
.br
.ti -1c
.RI "None \fBconvert_to_object\fP (self, list dicts, object object_type)"
.br
.ti -1c
.RI "None \fBset_players\fP (self)"
.br
.ti -1c
.RI "None \fBget_questions\fP (self)"
.br
.ti -1c
.RI "None \fBconvert_question_settings_to_api\fP (self)"
.br
.ti -1c
.RI "None \fBbegin\fP (self)"
.br
.ti -1c
.RI "None \fBshow_scores\fP (self)"
.br
.ti -1c
.RI "None \fBshow_question_markings\fP (self)"
.br
.ti -1c
.RI "None \fBmark_question\fP (self, user_input, current_user)"
.br
.ti -1c
.RI "None \fBplay\fP (self)"
.br
.ti -1c
.RI "None \fBnext_question\fP (self)"
.br
.ti -1c
.RI "bool \fBcheck_game_finished\fP (self)"
.br
.ti -1c
.RI "None \fBgame_end\fP (self)"
.br
.ti -1c
.RI "None \fBreset\fP (self)"
.br
.ti -1c
.RI "None \fBprepare_save_data\fP (self)"
.br
.ti -1c
.RI "None \fBsave\fP (self)"
.br
.ti -1c
.RI "None \fBconvert_all_from_save_data\fP (self)"
.br
.ti -1c
.RI "None \fBsettings_local\fP (self)"
.br
.ti -1c
.RI "None \fBsettings_networking\fP (self)"
.br
.ti -1c
.RI "None \fBsettings_gameplay\fP (self)"
.br
.ti -1c
.RI "def \fBwait_for_players\fP (self)"
.br
.ti -1c
.RI "def \fBjoin_game\fP (self, ip, port)"
.br
.ti -1c
.RI "bool \fBcheck_server_error\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgame_loaded\fP"
.br
.ti -1c
.RI "\fBonline_enabled\fP"
.br
.ti -1c
.RI "\fBhost_a_server\fP"
.br
.ti -1c
.RI "\fBtime_limit\fP"
.br
.ti -1c
.RI "\fBshow_score_after_question_or_game\fP"
.br
.ti -1c
.RI "\fBshow_correct_answer_after_question_or_game\fP"
.br
.ti -1c
.RI "\fBpoints_for_correct_answer\fP"
.br
.ti -1c
.RI "\fBpoints_for_incorrect_answer\fP"
.br
.ti -1c
.RI "\fBpoints_for_no_answer\fP"
.br
.ti -1c
.RI "\fBpoints_multiplier_for_a_streak\fP"
.br
.ti -1c
.RI "\fBpoints_multiplier_for_a_streak_base\fP"
.br
.ti -1c
.RI "\fBcompounding_amount_for_a_streak\fP"
.br
.ti -1c
.RI "\fBrandomise_questions\fP"
.br
.ti -1c
.RI "\fBrandomise_answer_placement\fP"
.br
.ti -1c
.RI "\fBpick_random_question\fP"
.br
.ti -1c
.RI "\fBbot_difficulty\fP"
.br
.ti -1c
.RI "\fBserver_name\fP"
.br
.ti -1c
.RI "\fBserver_port\fP"
.br
.ti -1c
.RI "\fBmax_players\fP"
.br
.ti -1c
.RI "\fBhow_many_players\fP"
.br
.ti -1c
.RI "\fBhow_many_bots\fP"
.br
.ti -1c
.RI "\fBquiz_category\fP"
.br
.ti -1c
.RI "\fBquiz_difficulty\fP"
.br
.ti -1c
.RI "\fBquestion_amount\fP"
.br
.ti -1c
.RI "\fBquestion_type\fP"
.br
.ti -1c
.RI "\fBcurrent_question\fP"
.br
.ti -1c
.RI "\fBcurrent_user_playing\fP"
.br
.ti -1c
.RI "\fBgame_finished\fP"
.br
.ti -1c
.RI "\fBjoined_game\fP"
.br
.ti -1c
.RI "\fBusers\fP"
.br
.ti -1c
.RI "\fBquestions\fP"
.br
.ti -1c
.RI "\fBbots\fP"
.br
.ti -1c
.RI "\fBapi_category\fP"
.br
.ti -1c
.RI "\fBapi_type\fP"
.br
.ti -1c
.RI "\fBgame_started\fP"
.br
.ti -1c
.RI "\fBsave_data\fP"
.br
.ti -1c
.RI "\fBcancelled\fP"
.br
.ti -1c
.RI "\fBbackend\fP"
.br
.ti -1c
.RI "\fBserver_thread\fP"
.br
.ti -1c
.RI "\fBcurrent_user_playing_net_name\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "None \fBhost_a_server\fP = None"
.br
.ti -1c
.RI "None \fBtime_limit\fP = None"
.br
.ti -1c
.RI "None \fBshow_score_after_question_or_game\fP = None"
.br
.ti -1c
.RI "None \fBshow_correct_answer_after_question_or_game\fP = None"
.br
.ti -1c
.RI "None \fBpoints_for_correct_answer\fP = None"
.br
.ti -1c
.RI "None \fBpoints_for_incorrect_answer\fP = None"
.br
.ti -1c
.RI "None \fBpoints_for_no_answer\fP = None"
.br
.ti -1c
.RI "None \fBpoints_multiplier_for_a_streak\fP = None"
.br
.ti -1c
.RI "None \fBpoints_multiplier_for_a_streak_base\fP = None"
.br
.ti -1c
.RI "None \fBcompounding_amount_for_a_streak\fP = None"
.br
.ti -1c
.RI "None \fBrandomise_questions\fP = None"
.br
.ti -1c
.RI "None \fBrandomise_answer_placement\fP = None"
.br
.ti -1c
.RI "None \fBpick_random_question\fP = None"
.br
.ti -1c
.RI "None \fBbot_difficulty\fP = None"
.br
.ti -1c
.RI "None \fBserver_name\fP = None"
.br
.ti -1c
.RI "None \fBserver_port\fP = None"
.br
.ti -1c
.RI "None \fBmax_players\fP = None"
.br
.ti -1c
.RI "None \fBhow_many_players\fP = None"
.br
.ti -1c
.RI "None \fBhow_many_bots\fP = None"
.br
.ti -1c
.RI "None \fBquiz_category\fP = None"
.br
.ti -1c
.RI "None \fBquiz_difficulty\fP = None"
.br
.ti -1c
.RI "None \fBquestion_amount\fP = None"
.br
.ti -1c
.RI "None \fBquestion_type\fP = None"
.br
.ti -1c
.RI "None \fBcurrent_question\fP = None"
.br
.ti -1c
.RI "None \fBcurrent_user_playing\fP = None"
.br
.ti -1c
.RI "None \fBcurrent_user_playing_net_name\fP = None"
.br
.ti -1c
.RI "None \fBonline_enabled\fP = None"
.br
.ti -1c
.RI "None \fBgame_finished\fP = None"
.br
.ti -1c
.RI "None \fBjoined_game\fP = None"
.br
.ti -1c
.RI "bool \fBgame_started\fP = False"
.br
.ti -1c
.RI "bool \fBgame_loaded\fP = False"
.br
.ti -1c
.RI "bool \fBcancelled\fP = False"
.br
.ti -1c
.RI "None \fBapi_category\fP = None"
.br
.ti -1c
.RI "None \fBapi_type\fP = None"
.br
.ti -1c
.RI "None \fBusers\fP = None"
.br
.ti -1c
.RI "None \fBquestions\fP = None"
.br
.ti -1c
.RI "None \fBbots\fP = None"
.br
.ti -1c
.RI "None \fBbackend\fP = None"
.br
.ti -1c
.RI "None \fBserver_thread\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB362\fP of file \fBgame\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None game\&.Game\&.__init__ ( self, str  quiz_save = \fCNone\fP)"

.PP
.nf
Creates a new game\&. If the quiz_save is not none, then load the quiz save because the user wants to continue a
game otherwise generate a new save file\&. After the save file is loaded, the default settings are set and then
converted into their relevant classes\&.

@param quiz_save: The name of the save file to load, if none then a new save file will be generated\&. (Default:
None)

.fi
.PP
 
.PP
Definition at line \fB410\fP of file \fBgame\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None game\&.Game\&.begin ( self)"

.PP
.nf
Starts the game\&. It first gets the questions if there are none, then shuffles the questions if the user wants
(only if the game is a new one as when continuing the game the questions should be in the same order)\&. If the
game is set to be hosted then a server is started up\&. Afterwards the game is checked to see if it is finished
othewise it will continue to play from the current state

.fi
.PP
 
.PP
Definition at line \fB653\fP of file \fBgame\&.py\fP\&.
.SS " bool game\&.Game\&.check_game_finished ( self)"

.PP
.nf
Checks if the game has finished and then will update the game_finished state\&. If the game has finished but
there are multiple players (locally) then it will reset the question counter and increase the current user
playing and then call play()
@return: True if the game has finished, False if not\&.

.fi
.PP
 
.PP
Definition at line \fB1089\fP of file \fBgame\&.py\fP\&.
.SS " bool game\&.Game\&.check_server_error ( self)"

.PP
.nf
Checks if the server has closed and if so then prints any errors and returns True\&. If the server is still
running and has no errors then returns False\&.
@return:

.fi
.PP
 
.PP
Definition at line \fB1552\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.convert_all_from_save_data ( self)"

.PP
.nf
Using the convert_to_object function the users, questions and bots are all attempted to be converted to their
relative classes

.fi
.PP
 
.PP
Definition at line \fB1221\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.convert_question_settings_to_api ( self)"

.PP
.nf
Since the API uses indices for the categories and lowercase strings for the types, this function converts the
user set settings into syntax that the API can understand

.fi
.PP
 
.PP
Definition at line \fB629\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.convert_to_object ( self, list dicts, object object_type)"

.PP
.nf
Converts the dicts list from a list of item to a list of object_type objects\&. It will only attempt convert
the item if it is not already a object_type object, therefore this function can be called without knowing the
state of each item in the list

.fi
.PP
 
.PP
Definition at line \fB535\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.game_end ( self)"

.PP
.nf
Shows a menu allowing for the final scores to be show or to compare the answers of the users\&.

.fi
.PP
 
.PP
Definition at line \fB1122\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.get_questions ( self)"

.PP
.nf
Gets the questions from the API or from the file depending on the online_enabled setting\&. Afterward it converts
the questions into Question objects and then shuffles the questions if the randomise_questions setting is True\&.
Finally, it saves the questions to the file\&.

.fi
.PP
 
.PP
Definition at line \fB595\fP of file \fBgame\&.py\fP\&.
.SS "def game\&.Game\&.join_game ( self,  ip,  port)"

.PP
.nf
Joins a game, by creating a socket and connecting to the server on the given ip and port\&. The game is then
ran when the server is ready\&. May return prematurely if an error occurs\&.

.fi
.PP
 
.PP
Definition at line \fB1496\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.load_from_saved ( self)"

.PP
.nf
Loads the game's variables from the saved data (self\&.save_data)

.fi
.PP
 
.PP
Definition at line \fB442\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.mark_question ( self,  user_input,  current_user)"

.PP
.nf
Marks the question and updates the user class based on the mark\&. The marking (Correct, Incorrect, Missed) is
added on to the current valued stored in the user's, answers array therefore before calling the marking
function set the string to be '' or 'Missed_'\&.

@param user_input: The answer submitted by the player, this is what will be checked against the correct answer
@param current_user: The user that answered the question, and where the points will be added to\&.

.fi
.PP
 
.PP
Definition at line \fB837\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.next_question ( self)"

.PP
.nf
Increases the current question by 1 and then checks if the game is over or not\&. If the game is over then it
will run the game_end() function\&. If the game is not over then it show the scores if specified so in
show_score_after_question_or_game and then will run the next question\&. If this is a network game then it will
wait for all the players to answer or for the server to move on\&.

.fi
.PP
 
.PP
Definition at line \fB1000\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.play ( self)"

.PP
.nf
Shows the user the question in a menu and gets the user to answer it, utilising the Menu class's time_limit
to force the user to answer in the specified amount of time\&. Then it marks the question and calculates the
score for the player\&. Afterwards it runs the next question\&. The start time and end time of this function is
calculated and then stored for later use to work out the timings for the stats\&.

.fi
.PP
 
.PP
Definition at line \fB902\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.prepare_save_data ( self)"

.PP
.nf
Prepares the save data for the game by converting the classes to dicts and removing the socket and thread
from the dictionary\&. Similar to convert_to_object() the state of each item is not needed to be the same as it
is compared using isinstance()\&.

.fi
.PP
 
.PP
Definition at line \fB1168\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.reset ( self)"

.PP
.nf
Resets the game back to a state that allows the game to be played again from the start\&. This will clear all user
 data but all settings and questions will be kept\&. The questions will be reshuffled is specified so

.fi
.PP
 
.PP
Definition at line \fB1144\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.save ( self)"

.PP
.nf
Saves the game data to the file\&. Calls the prepare_save_data() function so the game can be in any-state when
the caller is calling this function\&. After it has been written to the file the data is converted back\&.

.fi
.PP
 
.PP
Definition at line \fB1208\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.set_players ( self)"

.PP
.nf
Clears the list of users and bots, and then gets a colour and name for each user\&. The amount of users is set in
the settings menu\&. After the users have been set the bots are then created\&. The amount of bots is set in the
settings menu

.fi
.PP
 
.PP
Definition at line \fB552\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.set_settings ( self)"

.PP
.nf
Shows the user various menus related to settings, allowing them to change the settings\&. Starts with the main
gameplay settings menu

.fi
.PP
 
.PP
Definition at line \fB528\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.set_settings_default ( self)"

.PP
.nf
Sets the default settings if the settings are none

.fi
.PP
 
.PP
Definition at line \fB485\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.settings_gameplay ( self)"

.PP
.nf
Shows a menu to configure the gameplay settings for the game

.fi
.PP
 
.PP
Definition at line \fB1283\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.settings_local ( self)"

.PP
.nf
Shows a menu to configure the settings for a local hosted game

.fi
.PP
 
.PP
Definition at line \fB1232\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.settings_networking ( self)"

.PP
.nf
Shows a menu to configure the networking settings for the game
.fi
.PP
 
.PP
Definition at line \fB1252\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.show_question_markings ( self)"

.PP
.nf
Shows the answer each player submitted for the questions\&. It begins at current_question and then goes through each
question after that, so when called best practice is to set current_question to 0\&. It will call itself in a
loop until it reaches the end of the questions array

.fi
.PP
 
.PP
Definition at line \fB746\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Game\&.show_scores ( self)"

.PP
.nf
Shows the scores of all the players in a menu with the points beside them sorted from highest to lowest\&. If the
user selects a player their individual stats are show i\&.e accuracy and time etc\&.

.fi
.PP
 
.PP
Definition at line \fB680\fP of file \fBgame\&.py\fP\&.
.SS "def game\&.Game\&.wait_for_players ( self)"

.PP
.nf
Creates a new server and sets it to the backend of this class\&. If there are no players then the user is asked
to set the host player, otherwise whatever player is at index 0 will be set to the host\&. A menu is then
shown, showing all the players currently in the game, it refreshes itself every 3 seconds via manipulation
of the time_limit in the Menu class\&. When the host decides to start the game any old unconnected users will
be removed from the game and the game will start\&. The server will then sync the game data with the clients
and play() will be called\&.

.fi
.PP
 
.PP
Definition at line \fB1403\fP of file \fBgame\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "None game\&.Game\&.api_category = None\fC [static]\fP"

.PP
Definition at line \fB400\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.api_category"

.PP
Definition at line \fB640\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.api_type = None\fC [static]\fP"

.PP
Definition at line \fB401\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.api_type"

.PP
Definition at line \fB647\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.backend = None\fC [static]\fP"

.PP
Definition at line \fB407\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.backend"

.PP
Definition at line \fB1421\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.bot_difficulty = None\fC [static]\fP"

.PP
Definition at line \fB377\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.bot_difficulty"

.PP
Definition at line \fB463\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.bots = None\fC [static]\fP"

.PP
Definition at line \fB406\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.bots"

.PP
Definition at line \fB483\fP of file \fBgame\&.py\fP\&.
.SS "bool game\&.Game\&.cancelled = False\fC [static]\fP"

.PP
Definition at line \fB397\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.cancelled"

.PP
Definition at line \fB1400\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.compounding_amount_for_a_streak = None\fC [static]\fP"

.PP
Definition at line \fB373\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.compounding_amount_for_a_streak"

.PP
Definition at line \fB459\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.current_question = None\fC [static]\fP"

.PP
Definition at line \fB389\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.current_question"

.PP
Definition at line \fB475\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.current_user_playing = None\fC [static]\fP"

.PP
Definition at line \fB390\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.current_user_playing"

.PP
Definition at line \fB476\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.current_user_playing_net_name = None\fC [static]\fP"

.PP
Definition at line \fB391\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.current_user_playing_net_name"

.PP
Definition at line \fB1516\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.game_finished = None\fC [static]\fP"

.PP
Definition at line \fB393\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.game_finished"

.PP
Definition at line \fB477\fP of file \fBgame\&.py\fP\&.
.SS "bool game\&.Game\&.game_loaded = False\fC [static]\fP"

.PP
Definition at line \fB396\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.game_loaded"

.PP
Definition at line \fB425\fP of file \fBgame\&.py\fP\&.
.SS "bool game\&.Game\&.game_started = False\fC [static]\fP"

.PP
Definition at line \fB395\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.game_started"

.PP
Definition at line \fB677\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.host_a_server = None\fC [static]\fP"

.PP
Definition at line \fB364\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.host_a_server"

.PP
Definition at line \fB447\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.how_many_bots = None\fC [static]\fP"

.PP
Definition at line \fB382\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.how_many_bots"

.PP
Definition at line \fB468\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.how_many_players = None\fC [static]\fP"

.PP
Definition at line \fB381\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.how_many_players"

.PP
Definition at line \fB467\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.joined_game = None\fC [static]\fP"

.PP
Definition at line \fB394\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.joined_game"

.PP
Definition at line \fB478\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.max_players = None\fC [static]\fP"

.PP
Definition at line \fB380\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.max_players"

.PP
Definition at line \fB466\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.online_enabled = None\fC [static]\fP"

.PP
Definition at line \fB392\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.online_enabled"

.PP
Definition at line \fB431\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.pick_random_question = None\fC [static]\fP"

.PP
Definition at line \fB376\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.pick_random_question"

.PP
Definition at line \fB462\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.points_for_correct_answer = None\fC [static]\fP"

.PP
Definition at line \fB368\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.points_for_correct_answer"

.PP
Definition at line \fB453\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.points_for_incorrect_answer = None\fC [static]\fP"

.PP
Definition at line \fB369\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.points_for_incorrect_answer"

.PP
Definition at line \fB454\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.points_for_no_answer = None\fC [static]\fP"

.PP
Definition at line \fB370\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.points_for_no_answer"

.PP
Definition at line \fB455\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.points_multiplier_for_a_streak = None\fC [static]\fP"

.PP
Definition at line \fB371\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.points_multiplier_for_a_streak"

.PP
Definition at line \fB456\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.points_multiplier_for_a_streak_base = None\fC [static]\fP"

.PP
Definition at line \fB372\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.points_multiplier_for_a_streak_base"

.PP
Definition at line \fB457\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.question_amount = None\fC [static]\fP"

.PP
Definition at line \fB385\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.question_amount"

.PP
Definition at line \fB471\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.question_type = None\fC [static]\fP"

.PP
Definition at line \fB386\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.question_type"

.PP
Definition at line \fB472\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.questions = None\fC [static]\fP"

.PP
Definition at line \fB405\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.questions"

.PP
Definition at line \fB482\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.quiz_category = None\fC [static]\fP"

.PP
Definition at line \fB383\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.quiz_category"

.PP
Definition at line \fB469\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.quiz_difficulty = None\fC [static]\fP"

.PP
Definition at line \fB384\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.quiz_difficulty"

.PP
Definition at line \fB470\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.randomise_answer_placement = None\fC [static]\fP"

.PP
Definition at line \fB375\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.randomise_answer_placement"

.PP
Definition at line \fB461\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.randomise_questions = None\fC [static]\fP"

.PP
Definition at line \fB374\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.randomise_questions"

.PP
Definition at line \fB460\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.save_data"

.PP
Definition at line \fB1175\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.server_name = None\fC [static]\fP"

.PP
Definition at line \fB378\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.server_name"

.PP
Definition at line \fB464\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.server_port = None\fC [static]\fP"

.PP
Definition at line \fB379\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.server_port"

.PP
Definition at line \fB465\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.server_thread = None\fC [static]\fP"

.PP
Definition at line \fB408\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.server_thread"

.PP
Definition at line \fB1428\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.show_correct_answer_after_question_or_game = None\fC [static]\fP"

.PP
Definition at line \fB367\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.show_correct_answer_after_question_or_game"

.PP
Definition at line \fB451\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.show_score_after_question_or_game = None\fC [static]\fP"

.PP
Definition at line \fB366\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.show_score_after_question_or_game"

.PP
Definition at line \fB449\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.time_limit = None\fC [static]\fP"

.PP
Definition at line \fB365\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.time_limit"

.PP
Definition at line \fB448\fP of file \fBgame\&.py\fP\&.
.SS "None game\&.Game\&.users = None\fC [static]\fP"

.PP
Definition at line \fB404\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Game\&.users"

.PP
Definition at line \fB481\fP of file \fBgame\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
