.TH "game.Bot" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.Bot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgame\&.User\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__int__\fP (self, str \fBname\fP, str \fBcolour\fP, str \fBicon\fP, float \fBaccuracy\fP)"
.br
.ti -1c
.RI "None \fBload\fP (self, dict data)"
.br
.ti -1c
.RI "None \fBload_defaults\fP (self)"
.br
.ti -1c
.RI "None \fBshow_stats\fP (self)"
.br
.ti -1c
.RI "str \fBanswer\fP (self, \fBQuestion\fP question)"
.br
.in -1c

Public Member Functions inherited from \fBgame\&.User\fP
.in +1c
.ti -1c
.RI "None \fB__int__\fP (self, str \fBname\fP, str \fBcolour\fP, str \fBicon\fP)"
.br
.ti -1c
.RI "None \fBload\fP (self, dict data)"
.br
.ti -1c
.RI "None \fBload_defaults\fP (self)"
.br
.ti -1c
.RI "None \fBcalculate_stats\fP (self)"
.br
.ti -1c
.RI "None \fBshow_stats\fP (self)"
.br
.ti -1c
.RI "None \fBreset\fP (self)"
.br
.ti -1c
.RI "str \fBstyled_name\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaccuracy\fP"
.br
.ti -1c
.RI "\fBplayer_type\fP"
.br
.in -1c

Public Attributes inherited from \fBgame\&.User\fP
.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBcolour\fP"
.br
.ti -1c
.RI "\fBicon\fP"
.br
.ti -1c
.RI "\fBpoints\fP"
.br
.ti -1c
.RI "\fBcorrect\fP"
.br
.ti -1c
.RI "\fBincorrect\fP"
.br
.ti -1c
.RI "\fBstreak\fP"
.br
.ti -1c
.RI "\fBhighest_streak\fP"
.br
.ti -1c
.RI "\fBquestions_missed\fP"
.br
.ti -1c
.RI "\fBanswers\fP"
.br
.ti -1c
.RI "\fBtimes\fP"
.br
.ti -1c
.RI "\fBhas_answered\fP"
.br
.ti -1c
.RI "\fBquestions_answered\fP"
.br
.ti -1c
.RI "\fBaccuracy\fP"
.br
.ti -1c
.RI "\fBaverage_time\fP"
.br
.ti -1c
.RI "\fBaverage_time_correct\fP"
.br
.ti -1c
.RI "\fBaverage_time_incorrect\fP"
.br
.ti -1c
.RI "\fBaverage_time_missed\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "float \fBaccuracy\fP = 0\&.5"
.br
.in -1c

Static Public Attributes inherited from \fBgame\&.User\fP
.in +1c
.ti -1c
.RI "str \fBplayer_type\fP = 'User'"
.br
.ti -1c
.RI "None \fBname\fP = None"
.br
.ti -1c
.RI "None \fBcolour\fP = None"
.br
.ti -1c
.RI "None \fBicon\fP = None"
.br
.ti -1c
.RI "int \fBpoints\fP = 0"
.br
.ti -1c
.RI "int \fBcorrect\fP = 0"
.br
.ti -1c
.RI "int \fBincorrect\fP = 0"
.br
.ti -1c
.RI "int \fBstreak\fP = 0"
.br
.ti -1c
.RI "int \fBhighest_streak\fP = 0"
.br
.ti -1c
.RI "int \fBquestions_missed\fP = 0"
.br
.ti -1c
.RI "list \fBanswers\fP = []"
.br
.ti -1c
.RI "list \fBtimes\fP = []"
.br
.ti -1c
.RI "int \fBquestions_answered\fP = 0"
.br
.ti -1c
.RI "int \fBaverage_time\fP = 0"
.br
.ti -1c
.RI "int \fBaverage_time_correct\fP = 0"
.br
.ti -1c
.RI "int \fBaverage_time_incorrect\fP = 0"
.br
.ti -1c
.RI "int \fBaverage_time_missed\fP = 0"
.br
.ti -1c
.RI "int \fBaccuracy\fP = 0"
.br
.ti -1c
.RI "bool \fBis_host\fP = False"
.br
.ti -1c
.RI "bool \fBis_connected\fP = False"
.br
.ti -1c
.RI "bool \fBhas_answered\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB289\fP of file \fBgame\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None game\&.Bot\&.__int__ ( self, str name, str colour, str icon, float accuracy)"

.PP
.nf
Creates a new bot and assigns it a name, colour and icon

@param name: The name of the bot
@param colour: The colour of the bot
@param icon: The path to the icon of the bot
@param accuracy: How likely the bot is to get the question correct

.fi
.PP
 
.PP
Reimplemented from \fBgame\&.User\fP\&.
.PP
Definition at line \fB292\fP of file \fBgame\&.py\fP\&.
.SS " str game\&.Bot\&.answer ( self, \fBQuestion\fP question)"

.PP
.nf
Using the accuracy, the bot will return the correct answer if random\&.random() is less than the accuracy,
otherwise it will return a random incorrect answer

@param question: The question object where the bot should get its answer from
@return: The answer the bot chose

.fi
.PP
 
.PP
Definition at line \fB344\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Bot\&.load ( self, dict data)"

.PP
.nf
Loads the data from the dictionary into the bot using the function provided by the User class with the added
variable of accuracy\&. The defaults are then loaded\&.

@param data: The dictionary containing the data to load, should contain the same keys as the User\&.load()
function with an added accuracy key

.fi
.PP
 
.PP
Reimplemented from \fBgame\&.User\fP\&.
.PP
Definition at line \fB306\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Bot\&.load_defaults ( self)"

.PP
.nf
Loads the default values for the bot, the defaults are the same as the User class with the addition of an
default accuracy of 0\&.5 (50%)\&. Also sets the player_type to 'Bot'

.fi
.PP
 
.PP
Reimplemented from \fBgame\&.User\fP\&.
.PP
Definition at line \fB318\fP of file \fBgame\&.py\fP\&.
.SS " None game\&.Bot\&.show_stats ( self)"

.PP
.nf
Prints the collected stats variables to the console\&. The actual accuracy is printed and the expected accuracy
is also printed\&.

.fi
.PP
 
.PP
Reimplemented from \fBgame\&.User\fP\&.
.PP
Definition at line \fB327\fP of file \fBgame\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float game\&.Bot\&.accuracy = 0\&.5\fC [static]\fP"

.PP
Definition at line \fB290\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Bot\&.accuracy"

.PP
Definition at line \fB301\fP of file \fBgame\&.py\fP\&.
.SS "game\&.Bot\&.player_type"

.PP
Definition at line \fB325\fP of file \fBgame\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
