.TH "main.py" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmain\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBmain\&.game_finished\fP (Game game)"
.br
.ti -1c
.RI "None \fBmain\&.continue_game\fP ()"
.br
.ti -1c
.RI "None \fBmain\&.new_game\fP ()"
.br
.ti -1c
.RI "None \fBmain\&.join_game\fP ()"
.br
.ti -1c
.RI "None \fBmain\&.settings\fP ()"
.br
.ti -1c
.RI "None \fBmain\&.game_main_menu\fP ()"
.br
.ti -1c
.RI "None \fBmain\&.tutorial\fP ()"
.br
.ti -1c
.RI "None \fBmain\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBmain\&.data_folder\fP = 'UserData/'"
.br
.ti -1c
.RI "\fBmain\&.try\fP :"
.br
.ti -1c
.RI "\fBmain\&.finally\fP :"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
