.TH "md__documentation__code_doxygen_awesome_css_docs_tricks" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__documentation__code_doxygen_awesome_css_docs_tricks \- Tips & Tricks 
.PP

.SH "Diagrams with Graphviz"
.PP
To get the best looking class diagrams for your documentation, generate them with Graphviz as vector graphics with transparent background:
.PP
.PP
.nf
# Doxyfile
HAVE_DOT = YES
DOT_IMAGE_FORMAT = svg
DOT_TRANSPARENT = YES
.fi
.PP
.PP
In case \fCINTERACTIVE_SVG = YES\fP is set in the Doxyfile, all user-defined dotgraphs must be wrapped with the \fCinteractive_dotgraph\fP CSS class in order for them to be rendered correctly:
.PP
.PP
.nf
<div class="interactive_dotgraph">

\\dotfile graph\&.dot

</div>
.fi
.PP
.PP
\fBNote\fP
.RS 4
Both the default overflow scrolling behavior in this theme and the interactive editor enabled by \fCINTERACTIVE_SVG\fP are unsatisfying workarounds IMHO\&. Consider designing your graphs to be narrow enough to fit the page to avoid scrolling\&.
.RE
.PP
.SH "Disable Dark Mode"
.PP
If you don't want the theme to automatically switch to dark mode depending on the browser preference, you can disable dark mode by adding the \fClight-mode\fP class to the html-tag in the header template:
.PP
.PP
.nf
<html xmlns="http://www\&.w3\&.org/1999/xhtml" class="light\-mode">
.fi
.PP
.PP
The same can be done to always enable dark-mode:
.PP
.PP
.nf
<html xmlns="http://www\&.w3\&.org/1999/xhtml" class="dark\-mode">
.fi
.PP
.PP
\fBWarning\fP
.RS 4
This only works if you don't use the dark-mode toggle extension\&.
.RE
.PP
.SH "Choosing Sidebar Width"
.PP
If you have enabled the sidebar-only theme variant, make sure to carefully choose a proper width for your sidebar\&. It should be wide enough to hold the icon, project title and version number\&. If the content is too wide, it will be cut off\&.
.PP
.PP
.nf
html {
    /* Make sure sidebar is wide enough to contain the page title (logo + title + version) */
    \-\-side\-nav\-fixed\-width: 335px;
}
.fi
.PP
.PP
The chosen width should also be set in the Doxyfile:
.PP
.PP
.nf
# Doxyfile
TREEVIEW_WIDTH = 335
.fi
.PP
.SH "Formatting Tables"
.PP
By default tables in this theme are left-aligned and as wide as required to fit their content\&. Those properties can be changed for individual tables\&.
.SS "Centering"
Tables can be centered by wrapping them in the \fC<center>\fP HTML-tag\&.
.PP
.PP
.IP "\(bu" 2
Code 
.PP
.nf
<center>
    | This table | is centered          |
    |\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
    | test 1     | test 2               |
</center>

.fi
.PP

.IP "\(bu" 2
Result  This table   is centered    test 1   test 2   
.PP
.PP
.SS "Full Width"
To make tables span the full width of the page, no matter how wide the content is, wrap the table in the \fCfull_width_table\fP CSS class\&.
.PP
\fBWarning\fP
.RS 4
Apply with caution! This breaks the overflow scrolling of the table\&. Content might be cut of on small screens!
.RE
.PP
.PP
.IP "\(bu" 2
Code 
.PP
.nf
<div class="full_width_table">
    | This table | spans the full width |
    |\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
    | test 1     | test 2               |
</div>

.fi
.PP

.IP "\(bu" 2
Result  This table   spans the full width    test 1   test 2   
.PP
.PP
.PP
.PP
Read Next: \fCExample\fP  
