.TH "MyLibrary::SubclassExample< TemplatedClass >" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyLibrary::SubclassExample< TemplatedClass > \- some subclass  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <subclass\-example\&.hpp>\fP
.PP
Inherits \fBMyLibrary::Example\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBvirtualfunc\fP () override"
.br
.ti -1c
.RI "template<typename T > std::shared_ptr< std::string > \fBfunction_template_test\fP (std::shared_ptr< T > &param)"
.br
.RI "Template function function\&. "
.ti -1c
.RI "template<typename T , typename Foo , typename Bar , typename Alice , typename Bob , typename Charlie , typename Hello , typename World > std::pair< std::string, std::string > \fBlong_function_with_many_parameters\fP (std::shared_ptr< T > &param1, std::shared_ptr< std::string > &param2, bool parameter3, Alice paramater4 Bob parameter 5)"
.br
.RI "Extra long function with lots of parameters and many template types\&. "
.in -1c

Public Member Functions inherited from \fBMyLibrary::Example\fP
.in +1c
.ti -1c
.RI "std::string \fBtest\fP (const std::string &test)"
.br
.RI "brief summary "
.ti -1c
.RI "virtual int \fBvirtualfunc\fP ()=0"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBMyLibrary::Example\fP
.in +1c
.ti -1c
.RI "static bool \fBstaticfunc\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TemplatedClass>
.br
class MyLibrary::SubclassExample< TemplatedClass >"some subclass 
.PP
Definition at line \fB12\fP of file \fBsubclass\-example\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename TemplatedClass > template<typename T > std::shared_ptr< std::string > \fBMyLibrary::SubclassExample\fP< TemplatedClass >::function_template_test (std::shared_ptr< T > & param)"

.PP
Template function function\&. 
.SS "template<typename TemplatedClass > template<typename T , typename Foo , typename Bar , typename Alice , typename Bob , typename Charlie , typename Hello , typename World > std::pair< std::string, std::string > \fBMyLibrary::SubclassExample\fP< TemplatedClass >::long_function_with_many_parameters (std::shared_ptr< T > & param1, std::shared_ptr< std::string > & param2, bool parameter3, Alice paramater4 Bob parameter 5)\fC [inline]\fP"

.PP
Extra long function with lots of parameters and many template types\&. Also has a long return type\&.
.PP
\fBParameters\fP
.RS 4
\fIparam1\fP first parameter 
.br
\fIparam2\fP second parameter 
.br
\fIparameter3\fP third parameter 
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBsubclass\-example\&.hpp\fP\&.
.SS "template<typename TemplatedClass > int \fBMyLibrary::SubclassExample\fP< TemplatedClass >::virtualfunc ()\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBBug\fP
.RS 4
second bug 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBMyLibrary::Example\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
