.TH "MyLibrary" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyLibrary
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExample\fP"
.br
.RI "\fBExample\fP class to demonstrate the features of the custom CSS\&. "
.ti -1c
.RI "class \fBSubclassExample\fP"
.br
.RI "some subclass "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBColor\fP { \fBred\fP, \fBgreen\fP, \fBblue\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMyLibrary::Color\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIred \fP\fP
.TP
\fB\fIgreen \fP\fP
.TP
\fB\fIblue \fP\fP
.PP
Definition at line \fB6\fP of file \fBexample\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
