.TH "network.QuizGameClient" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network.QuizGameClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBnetwork\&.QuizClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, str \fBhost\fP, int \fBport\fP)"
.br
.ti -1c
.RI "None \fBhandle_data_received\fP (self, socket sock, object key_data, bytes recv_data)"
.br
.ti -1c
.RI "None \fBhandle_error\fP (self, socket sock, object key_data, Exception error_response)"
.br
.ti -1c
.RI "def \fBsend_self\fP (self)"
.br
.ti -1c
.RI "def \fBwait_for_move_on\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBnetwork\&.QuizClient\fP
.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, str \fBhost\fP, int \fBport\fP)"
.br
.ti -1c
.RI "None \fBrun\fP (self)"
.br
.ti -1c
.RI "None \fBclose_connection\fP (self, socket sock)"
.br
.ti -1c
.RI "None \fBhandle_data_received\fP (self, socket sock, object key_data, bytes recv_data)"
.br
.ti -1c
.RI "None \fBhandle_request\fP (self, socket sock, object key_data, bytes send_data)"
.br
.ti -1c
.RI "None \fBhandle_error\fP (self, socket sock, object key_data, Exception error_response)"
.br
.ti -1c
.RI "None \fBsend_message\fP (self, object sock, str message, str message_type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBserver\fP"
.br
.ti -1c
.RI "\fBerror\fP"
.br
.ti -1c
.RI "\fBrunning\fP"
.br
.ti -1c
.RI "\fBmove_on\fP"
.br
.in -1c

Public Attributes inherited from \fBnetwork\&.QuizClient\fP
.in +1c
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBselector\fP"
.br
.ti -1c
.RI "\fBclient\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "None \fBgame\fP = None"
.br
.ti -1c
.RI "bool \fBrunning\fP = False"
.br
.ti -1c
.RI "None \fBerror\fP = None"
.br
.ti -1c
.RI "None \fBserver\fP = None"
.br
.ti -1c
.RI "bool \fBmove_on\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB618\fP of file \fBnetwork\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def network\&.QuizGameClient\&.__init__ ( self, str host, int port)"

.PP
.nf
Initialise the client and connect to the server\&. The selector set and then is used to listen for data from
the server

@param host: The host ip to connect to
@param port: The port to listen on

.fi
.PP
 
.PP
Reimplemented from \fBnetwork\&.QuizClient\fP\&.
.PP
Definition at line \fB625\fP of file \fBnetwork\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " None network\&.QuizGameClient\&.handle_data_received ( self, socket sock, object key_data, bytes recv_data)"

.PP
.nf
Handle data received from the server\&. The message is converted to a QuizMessage object and then handled,
the types that can be handled are: server_error, move_on, sync_game, sync_players, sync_bots\&. Server error
will cause the client to close, move on will exit the wait_for_move_on()'s loop, sync_game will sync the game
data, sync_players will sync the player data and sync_bots will sync the bot data\&.

@param sock: The socket to handle the data from
@param key_data: The key data for the socket's selector
@param recv_data: The data received from the server as bytes (the same as key_data\&.receive_bytes but kept for
convenience)

.fi
.PP
 
.PP
Reimplemented from \fBnetwork\&.QuizClient\fP\&.
.PP
Definition at line \fB628\fP of file \fBnetwork\&.py\fP\&.
.SS " None network\&.QuizGameClient\&.handle_error ( self, socket sock, object key_data, Exception error_response)"

.PP
.nf
Handle an error from the server, close the connection and set the running variable to false\&. If the error
message was that the connection was closed by the host then it is rephrased as 'Server Closed' for readability\&.

@param sock: The socket to handle the error from
@param key_data: The key data for the socket
@param error_response: The error response

.fi
.PP
 
.PP
Reimplemented from \fBnetwork\&.QuizClient\fP\&.
.PP
Definition at line \fB698\fP of file \fBnetwork\&.py\fP\&.
.SS "def network\&.QuizGameClient\&.send_self ( self)"

.PP
.nf
Send the local user to the server

.fi
.PP
 
.PP
Definition at line \fB718\fP of file \fBnetwork\&.py\fP\&.
.SS "def network\&.QuizGameClient\&.wait_for_move_on ( self)"

.PP
.nf
Wait for the move on flag to be set (this is set when receiving the move on message from the server)

.fi
.PP
 
.PP
Definition at line \fB734\fP of file \fBnetwork\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "None network\&.QuizGameClient\&.error = None\fC [static]\fP"

.PP
Definition at line \fB621\fP of file \fBnetwork\&.py\fP\&.
.SS "network\&.QuizGameClient\&.error"

.PP
Definition at line \fB649\fP of file \fBnetwork\&.py\fP\&.
.SS "None network\&.QuizGameClient\&.game = None\fC [static]\fP"

.PP
Definition at line \fB619\fP of file \fBnetwork\&.py\fP\&.
.SS "bool network\&.QuizGameClient\&.move_on = False\fC [static]\fP"

.PP
Definition at line \fB623\fP of file \fBnetwork\&.py\fP\&.
.SS "network\&.QuizGameClient\&.move_on"

.PP
Definition at line \fB654\fP of file \fBnetwork\&.py\fP\&.
.SS "bool network\&.QuizGameClient\&.running = False\fC [static]\fP"

.PP
Definition at line \fB620\fP of file \fBnetwork\&.py\fP\&.
.SS "network\&.QuizGameClient\&.running"

.PP
Definition at line \fB651\fP of file \fBnetwork\&.py\fP\&.
.SS "None network\&.QuizGameClient\&.server = None\fC [static]\fP"

.PP
Definition at line \fB622\fP of file \fBnetwork\&.py\fP\&.
.SS "network\&.QuizGameClient\&.server"

.PP
Definition at line \fB640\fP of file \fBnetwork\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
