.TH "renderer.WrapMode" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderer.WrapMode
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNONE\fP = 0"
.br
.ti -1c
.RI "int \fBCHAR\fP = 1"
.br
.ti -1c
.RI "int \fBWORD\fP = 2"
.br
.ti -1c
.RI "int \fBTRUNCATE\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A class that stores shorthands for the styling to preform when text is larger than the console width

.fi
.PP
 
.PP
Definition at line \fB24\fP of file \fBrenderer\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int renderer\&.WrapMode\&.CHAR = 1\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBrenderer\&.py\fP\&.
.SS "int renderer\&.WrapMode\&.NONE = 0\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBrenderer\&.py\fP\&.
.SS "int renderer\&.WrapMode\&.TRUNCATE = 2\fC [static]\fP"

.PP
Definition at line \fB31\fP of file \fBrenderer\&.py\fP\&.
.SS "int renderer\&.WrapMode\&.WORD = 2\fC [static]\fP"

.PP
Definition at line \fB30\fP of file \fBrenderer\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
