.TH "renderer.MenuManager" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderer.MenuManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBmenu_history_names\fP = []"
.br
.ti -1c
.RI "list \fBmenu_history_input\fP = []"
.br
.ti -1c
.RI "list \fBpre_input\fP = []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB121\fP of file \fBrenderer\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "list renderer\&.MenuManager\&.menu_history_input = []\fC [static]\fP"

.PP
Definition at line \fB123\fP of file \fBrenderer\&.py\fP\&.
.SS "list renderer\&.MenuManager\&.menu_history_names = []\fC [static]\fP"

.PP
Definition at line \fB122\fP of file \fBrenderer\&.py\fP\&.
.SS "list renderer\&.MenuManager\&.pre_input = []\fC [static]\fP"

.PP
Definition at line \fB124\fP of file \fBrenderer\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
