.TH "Documentation/Code/doxygen-awesome-css/docs/tricks.md" 3 "Sat Mar 11 2023" "Version 0.54" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documentation/Code/doxygen-awesome-css/docs/tricks.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
