.TH "Maxs_Modules Directory Reference" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Maxs_Modules Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdebug\&.py\fP"
.br
.ti -1c
.RI "file \fBfiles\&.py\fP"
.br
.ti -1c
.RI "file \fBgame\&.py\fP"
.br
.ti -1c
.RI "file \fBnetwork\&.py\fP"
.br
.ti -1c
.RI "file \fBrenderer\&.py\fP"
.br
.ti -1c
.RI "file \fBtools\&.py\fP"
.br
.in -1c
