.TH "main" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBgame_finished\fP (Game game)"
.br
.ti -1c
.RI "None \fBcontinue_game\fP ()"
.br
.ti -1c
.RI "None \fBnew_game\fP ()"
.br
.ti -1c
.RI "None \fBjoin_game\fP ()"
.br
.ti -1c
.RI "None \fBsettings\fP ()"
.br
.ti -1c
.RI "None \fBgame_main_menu\fP ()"
.br
.ti -1c
.RI "None \fBtutorial\fP ()"
.br
.ti -1c
.RI "None \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBdata_folder\fP = 'UserData/'"
.br
.ti -1c
.RI "\fBtry\fP :"
.br
.ti -1c
.RI "\fBfinally\fP :"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " None main\&.continue_game ()"

.PP
.nf
Shows a menu that allows the user to continue a game, It allows the user to select a game from the saved games
folder, if the user selects a previously joined multiplayer game it will delete the save file and join the game
instead of continuing

.fi
.PP
 
.PP
Definition at line \fB82\fP of file \fBmain\&.py\fP\&.
.SS " None main\&.game_finished (Game game)"

.PP
.nf
Shows a menu that allows the user to play again or return to the main menu, if the game does not have the
game_finished variable set to True, it will only return to the main menu without letting the user choosing an option
\&. Play again resets the game and calls the game\&.begin() function, once the reset game is finished the input loop
will run again (using the same game object)\&. When returning to the main menu the game\&.save_file will be deleted if
it exists

@param game: The Game object to use\&.
@return: None, the function will break the loop when the user selects an option that leaves the menu

.fi
.PP
 
.PP
Definition at line \fB40\fP of file \fBmain\&.py\fP\&.
.SS " None main\&.game_main_menu ()"

.PP
.nf
Show the user the main menu, allowing them to continue a game, start a new game, join a game, view the tutorial or
quit

.fi
.PP
 
.PP
Definition at line \fB230\fP of file \fBmain\&.py\fP\&.
.SS " None main\&.join_game ()"

.PP
.nf
Shows the user a menu to join a game, the user can enter the ip and port of the server to join\&. The default values
are the local ip and port 1234 as that is the default port for the server\&.

.fi
.PP
 
.PP
Definition at line \fB146\fP of file \fBmain\&.py\fP\&.
.SS " None main\&.main ()"

.PP
.nf
The main function, initialise the program and show the main menu

.fi
.PP
 
.PP
Definition at line \fB341\fP of file \fBmain\&.py\fP\&.
.SS " None main\&.new_game ()"

.PP
.nf
Creates a new game object, runs the settings setup and then starts the game (if not cancelled during settings)

.fi
.PP
 
.PP
Definition at line \fB128\fP of file \fBmain\&.py\fP\&.
.SS " None main\&.settings ()"

.PP
.nf
Show the user a menu that allows them to change their already specified settings

.fi
.PP
 
.PP
Definition at line \fB188\fP of file \fBmain\&.py\fP\&.
.SS " None main\&.tutorial ()"

.PP
.nf
Show the user a tutorial on how to use the menus, host a game and join a game

.fi
.PP
 
.PP
Definition at line \fB272\fP of file \fBmain\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "str main\&.data_folder = 'UserData/'"

.PP
Definition at line \fB32\fP of file \fBmain\&.py\fP\&.
.SS "main\&.finally :"

.PP
Definition at line \fB368\fP of file \fBmain\&.py\fP\&.
.SS "main\&.try :"

.PP
Definition at line \fB366\fP of file \fBmain\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
