.TH "Maxs_Modules/network.py" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Maxs_Modules/network.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnetwork\&.QuizMessage\fP"
.br
.ti -1c
.RI "class \fBnetwork\&.QuizServer\fP"
.br
.ti -1c
.RI "class \fBnetwork\&.QuizClient\fP"
.br
.ti -1c
.RI "class \fBnetwork\&.QuizGameServer\fP"
.br
.ti -1c
.RI "class \fBnetwork\&.QuizGameClient\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnetwork\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list \fBnetwork\&.api_get_questions\fP (int amount, int category, str difficulty, str question_type)"
.br
.ti -1c
.RI "socket\&.socket \fBnetwork\&.connect_to_server\fP (str server_ip, int port)"
.br
.ti -1c
.RI "socket\&.socket \fBnetwork\&.setup_tcp_server\fP (int port)"
.br
.ti -1c
.RI "str \fBnetwork\&.get_ip\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
