.TH "renderer.Menu" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderer.Menu
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "None \fB__init__\fP (self, str \fBtitle\fP, list|tuple \fBitems\fP, bool \fBmulti_dimensional\fP=False)"
.br
.ti -1c
.RI "list \fBshow_menu\fP (self)"
.br
.ti -1c
.RI "str \fBget_input\fP (self, str \fBuser_input\fP=None)"
.br
.ti -1c
.RI "list \fBget_pages\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBitems\fP"
.br
.ti -1c
.RI "\fBmulti_dimensional\fP"
.br
.ti -1c
.RI "\fBuser_input\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBtitle\fP = 'None'"
.br
.ti -1c
.RI "list \fBitems\fP = []"
.br
.ti -1c
.RI "str \fBuser_input\fP = 'undefined'"
.br
.ti -1c
.RI "bool \fBclear_screen\fP = True"
.br
.ti -1c
.RI "None \fBmulti_dimensional\fP = None"
.br
.ti -1c
.RI "\fBWrapMode\fP \fBwrap_mode\fP = \fBWrapMode\&.WORD\fP"
.br
.ti -1c
.RI "int \fBpage_number\fP = 1"
.br
.ti -1c
.RI "\fBmax_menu_items_per_page\fP \fBitems_per_page\fP = \fBmax_menu_items_per_page\fP"
.br
.ti -1c
.RI "int \fBtime_limit\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB137\fP of file \fBrenderer\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS " None renderer\&.Menu\&.__init__ ( self, str title, list | tuple items, bool  multi_dimensional = \fCFalse\fP)"

.PP
.nf
Creates a menu object

@param title: The title of the menu
@param items: The items in the menu, if multi_dimensional is True then the items should be a list of lists
@param multi_dimensional: If the menu items array is multi-dimensional (i\&.e\&. has a value for each item)

.fi
.PP
 
.PP
Definition at line \fB154\fP of file \fBrenderer\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " str renderer\&.Menu\&.get_input ( self, str  user_input = \fCNone\fP)"

.PP
.nf
Prints the menu to a clear screen and then gets the user input as an index of the menu items\&. Then stores the
item in the user_input variable\&. If the user input is invalid then it will ask the user to try again until it
is valid\&. Valid input is an integer between 0 and the length of the menu items array, or a string that is in
the menu items array\&. If input is passed in then it will not ask the user for input and will instead use the
input passed in (if it is not valid then it will ask)\&. If the time_limit is set to a value greater than 0 then
it will return after the time limit has been reached (if the user has not input anything before that)\&.
Pre-input allows for the user to input a list of indexes that will be automatically used as the user input\&.

@param user_input: The user input to use instead of getting input from the user\&.
@return: The option the user selected (the item in the menu items array)

.fi
.PP
 
.PP
Definition at line \fB190\fP of file \fBrenderer\&.py\fP\&.
.SS " list renderer\&.Menu\&.get_pages ( self)"

.PP
.nf
Splits the menu items into pages if there are more than the max menu items in the list of items\&. Curently not
working will be fixed or removed later

@return: The current page of menu items (a list of 10 options, including previous and next page)

.fi
.PP
 
.PP
Definition at line \fB359\fP of file \fBrenderer\&.py\fP\&.
.SS " list renderer\&.Menu\&.show_menu ( self)"

.PP
.nf
Prints the menu to a clear screen\&. Automatically uses the multi_dimensional variable to determine if the menu
should use show_menu_double or show_menu

.fi
.PP
 
.PP
Definition at line \fB167\fP of file \fBrenderer\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool renderer\&.Menu\&.clear_screen = True\fC [static]\fP"

.PP
Definition at line \fB147\fP of file \fBrenderer\&.py\fP\&.
.SS "list renderer\&.Menu\&.items = []\fC [static]\fP"

.PP
Definition at line \fB143\fP of file \fBrenderer\&.py\fP\&.
.SS "renderer\&.Menu\&.items"

.PP
Definition at line \fB163\fP of file \fBrenderer\&.py\fP\&.
.SS "\fBmax_menu_items_per_page\fP renderer\&.Menu\&.items_per_page = \fBmax_menu_items_per_page\fP\fC [static]\fP"

.PP
Definition at line \fB151\fP of file \fBrenderer\&.py\fP\&.
.SS "None renderer\&.Menu\&.multi_dimensional = None\fC [static]\fP"

.PP
Definition at line \fB148\fP of file \fBrenderer\&.py\fP\&.
.SS "renderer\&.Menu\&.multi_dimensional"

.PP
Definition at line \fB164\fP of file \fBrenderer\&.py\fP\&.
.SS "int renderer\&.Menu\&.page_number = 1\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBrenderer\&.py\fP\&.
.SS "int renderer\&.Menu\&.time_limit = 0\fC [static]\fP"

.PP
Definition at line \fB152\fP of file \fBrenderer\&.py\fP\&.
.SS "str renderer\&.Menu\&.title = 'None'\fC [static]\fP"

.PP
Definition at line \fB142\fP of file \fBrenderer\&.py\fP\&.
.SS "renderer\&.Menu\&.title"

.PP
Definition at line \fB162\fP of file \fBrenderer\&.py\fP\&.
.SS "str renderer\&.Menu\&.user_input = 'undefined'\fC [static]\fP"

.PP
Definition at line \fB144\fP of file \fBrenderer\&.py\fP\&.
.SS "renderer\&.Menu\&.user_input"

.PP
Definition at line \fB225\fP of file \fBrenderer\&.py\fP\&.
.SS "\fBWrapMode\fP renderer\&.Menu\&.wrap_mode = \fBWrapMode\&.WORD\fP\fC [static]\fP"

.PP
Definition at line \fB149\fP of file \fBrenderer\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
