.TH "Maxs_Modules/tools.py" 3 "Sun Mar 12 2023" "Version 0.55" "Quiz Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Maxs_Modules/tools.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtools\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "list \fBtools\&.sort_multi_array\fP (list data, bool descending=False)"
.br
.ti -1c
.RI "bool \fBtools\&.string_bool\fP (str text)"
.br
.ti -1c
.RI "Exception or str \fBtools\&.ip_address\fP (str text)"
.br
.ti -1c
.RI "object \fBtools\&.get_user_input_of_type\fP (object type_to_convert, str input_message='', list must_be_one_of_these=None, list allow_these=None, int max_time=0)"
.br
.ti -1c
.RI "object \fBtools\&.set_if_none\fP (object variable, object value)"
.br
.ti -1c
.RI "object \fBtools\&.try_convert\fP (object variable, type type_to_convert, bool supress_errors=False)"
.br
.ti -1c
.RI "None \fBtools\&.install_package\fP (str package)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBtools\&.imported_timeout\fP = False"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz Game from the source code\&.
